### ISSUE TITLE
Retail: Destruction Warlock / Demonology Warlock

### ISSUE THREAD

**Issue by Stitchypoo** [jrubimf/ERZ_Issues#17]
1) Destruction warlock auto bind not working for Rain of Fire and cataclysm, I press the key that it is auto binded to, and nothing happens, works for every other spell though.

2) Demonology warlock: explodes/wastes all imps on a dead target, saving the imps is better when you are going to the next mob pack/boss. Demonology pet not using kick (axe toss).

**Comment by jrubimf** [comment]
All fixed.
